name       : qt5-graphicaleffects
version    : 5.15.9
release    : 29
source     :
    - git|https://invent.kde.org/qt/qt/qtgraphicaleffects.git : 06cfcbb6940d2729f5a6575e264873ce65ac99c3
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Graphical Effects Module
description: |
    The Qt Graphical Effects module provides a set of QML types for adding visually impressive and configurable effects to user interfaces. Effects are visual items that can be added to Qt Quick user interface as UI components.
    The API consists of over 20 effects provided as separate QML types. The effects cover functional areas such as blending, masking, blurring, coloring, and many more.
builddeps  :
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %qmake CONFIG+=release qtgraphicaleffects.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    %qml_cache
