name       : qt5-graphicaleffects
version    : 5.13.2
release    : 18
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtgraphicaleffects-everywhere-src-5.13.2.tar.xz : 297a89bb6c771f849c4ce866e5c98dadf665163b3dab03bc48a58f51424e7e66
homepage   : https://www.qt.io
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Graphical Effects Module
description: |
    The Qt Graphical Effects module provides a set of QML types for adding visually impressive and configurable effects to user interfaces. Effects are visual items that can be added to Qt Quick user interface as UI components.

    The API consists of over 20 effects provided as separate QML types. The effects cover functional areas such as blending, masking, blurring, coloring, and many more.
builddeps  :
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %qmake CONFIG+=release qtgraphicaleffects.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    %qml_cache
