name       : qt5-graphicaleffects
version    : 5.12.1
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtgraphicaleffects-everywhere-src-5.12.1.tar.xz : 2e63abf6b02b86461b73b317eba00b6721601a9469c22da28e3f4ea1d5df68d7
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Graphical Effects Module
description: |
    The Qt Graphical Effects module provides a set of QML types for adding visually impressive and configurable effects to user interfaces. Effects are visual items that can be added to Qt Quick user interface as UI components.

    The API consists of over 20 effects provided as separate QML types. The effects cover functional areas such as blending, masking, blurring, coloring, and many more.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %qmake CONFIG+=release qtgraphicaleffects.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    %qml_cache
